Repository rust-lang/futures-rs, pull requests merged in 2022-05, with the labels that each got.

#2583 Remove `Fuse`s from `select`, and only poll non-terminated streams
  futures-util/Cargo.toml
  futures-util/src/stream/select_with_strategy.rs
Labels: A-stream, 0.3-backport: pending

#2593 Make run_until_stalled handle self-waking futures
  futures-executor/src/local_pool.rs
  futures-executor/tests/local_pool.rs
Labels: A-executor, 0.3-backport: pending

#2602 Fix rustdoc::broken_intra_doc_links warning
  futures-util/src/future/try_future/mod.rs
  futures-util/src/stream/stream/mod.rs
Labels: docs, 0.3-backport: pending

#2590 Several tweaks
  futures-util/src/stream/stream/flatten_unordered.rs
  futures-util/src/stream/try_stream/try_flatten_unordered.rs
Labels: 0.3-backport: pending

#2604 Fix minor typo in enter doc comment
  futures-executor/src/enter.rs
Labels: docs
